export const IMAGE_UPLOAD_REQUEST= 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS= 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_FAIL= 'IMAGE_UPLOAD_FAIL'



export const IMAGE_IMPORT_SUCCESS= 'IMAGE_IMPORT_SUCCESS'
export const IMAGE_IMPORT_FAIL= 'IMAGE_IMPORT_FAIL'


export const IMAGE_UPDATE_REQUEST= 'IMAGE_UPDATE_REQUEST'
export const IMAGE_UPDATE_SUCCESS= 'IMAGE_UPDATE_SUCCESS'
export const IMAGE_UPDATE_FAIL= 'IMAGE_UPDATE_FAIL'

