export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const CUSGET_PROFILE_REQUEST = 'CUSGET_PROFILE_REQUEST'
export const CUSGET_PROFILE_SUCCESS = 'CUSGET_PROFILE_SUCCESS'
export const CUSGET_PROFILE_FAIL = 'CUSGET_PROFILE_FAIL'

export const CUSUPDATE_PROFILE_REQUEST = 'CUSUPDATE_PROFILE_REQUEST'
export const CUSUPDATE_PROFILE_SUCCESS = 'CUSUPDATE_PROFILE_SUCCESS'
export const CUSUPDATE_PROFILE_FAIL = 'CUSUPDATE_PROFILE_FAIL'

export const CUSGET_PAYMENT_REQUEST = 'CUSGET_PAYMENT_REQUEST'
export const CUSGET_PAYMENT_SUCCESS = 'CUSGET_PAYMENT_SUCCESS'
export const CUSGET_PAYMENT_FAIL = 'CUSGET_PAYMENT_FAIL'

export const CUSDELE_PAYMENT_REQUEST = 'CUSDELE_PAYMENT_REQUEST'
export const CUSDELE_PAYMENT_SUCCESS = 'CUSDELE_PAYMENT_SUCCESS'
export const CUSDELE_PAYMENT_FAIL = 'CUSDELE_PAYMENT_FAIL'

export const LIST_D_NOTI_REQUEST = 'LIST_D_NOTI_REQUEST'
export const LIST_D_NOTI_SUCCESS = 'LIST_D_NOTI_SUCCESS'
export const LIST_D_NOTI_FAIL = 'LIST_D_NOTI_FAIL'

export const LIST_M_NOTI_REQUEST = 'LIST_M_NOTI_REQUEST'
export const LIST_M_NOTI_SUCCESS = 'LIST_M_NOTI_SUCCESS'
export const LIST_M_NOTI_FAIL = 'LIST_M_NOTI_FAIL'

export const UPDATE_D_NOTI_REQUEST = 'UPDATE_D_NOTI_REQUEST'
export const UPDATE_D_NOTI_SUCCESS = 'UPDATE_D_NOTI_SUCCESS'
export const UPDATE_D_NOTI_FAIL = 'UPDATE_D_NOTI_FAIL'

export const UPDATE_M_NOTI_REQUEST = 'UPDATE_M_NOTI_REQUEST'
export const UPDATE_M_NOTI_SUCCESS = 'UPDATE_M_NOTI_SUCCESS'
export const UPDATE_M_NOTI_FAIL = 'UPDATE_M_NOTI_FAIL'
